tabela_brasileirao = ('Palmeiras', 'Flamengo', 'Internacional', 'Grêmio', 'São Paulo', 'Atlético-MG', 'Athletico-PR', 'Cruzeiro', 'Botafogo',
                      'Santos', 'Bahia', 'Fluminense', 'Corinthians', 'Chapecoense', 'Ceará', 'Vasco', 'Sport', 'América-MG', 'Vitória', 'Paraná')
print('=' * 80)
print('{:^80}'.format('DADOS BRASILEIRÃO 2018'))
print('=' * 80)
print('\nOs primeiros 5 colocados são:')
print('-' * 80)
print(f'{tabela_brasileirao[0:5]}')
print('-' * 80)
print('\nOs últimos 4 colocados são:')
print('-' * 80)
print(f'{tabela_brasileirao[-4:]}')
print('-' * 80)
print('\nTimes em ordem alfabética: ')
print('-' * 80)
print(f'{sorted(tabela_brasileirao)}')
print('-' * 80)
print('\nO Chapecoense está na posição: {}'.format(tabela_brasileirao.index('Chapecoense') + 1))
print(f'\nO Chapecoense está na posição: {tabela_brasileirao.index("Chapecoense") + 1}')  # Can't use ' inside another '
